
mybatis:
  #注册映射文件
  mapper-locations: classpath:com/bos/source/mapper/*.xml
  #注册实体类别名
  type-aliases-package: com.bos.source.model
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///vhr   #jdbc:mysql:///test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
server:
  port: 8888
logging:
  config: classpath:logback-spring.xml
